#!/bin/bash

DIRECTORY="./test/"
PREFIXES=(15000 15100 15200)
EXAMPLE_SUFFIX=".good"
OUTPUT_SUFFIX=".txt"

for file in "${PREFIXES[@]}"
do
    rm $file$OUTPUT_SUFFIX
done

awk -f ./src/script.awk < ./test/file_in


for file in "${PREFIXES[@]}"
do
    diff $DIRECTORY$file$EXAMPLE_SUFFIX $file$OUTPUT_SUFFIX
done
